In [46]:
import nibabel as nib
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

In [2]:
img = nib.load("/home/gabridele/Desktop/storage_folder/spreading_dynamics_clinical/derivatives/templates/Schaefer2018_400Parcels_Tian_Subcortex_S4_1mm.nii.gz")

In [4]:
print(img)


<class 'nibabel.nifti1.Nifti1Image'>
data shape (182, 218, 182)
affine:
[[  -1.    0.    0.   90.]
 [   0.    1.    0. -126.]
 [   0.    0.    1.  -72.]
 [   0.    0.    0.    1.]]
metadata:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b'          '
db_name         : b'                  '
extents         : 16384
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3 182 218 182   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.  1.  1.  1.  1.  1.  1.  1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 10
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'5.0.10                       

In [33]:
atlas = img.get_fdata()
#img_nifti = np.array(img.dataobj)

roi_labels = np.unique(atlas)
roi_labels = roi_labels[roi_labels != 0]  # Assuming 0 is not a valid ROI
print(roi_labels)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100. 101. 102. 103. 104. 105. 106. 107. 108. 109. 110. 111. 112.
 113. 114. 115. 116. 117. 118. 119. 120. 121. 122. 123. 124. 125. 126.
 127. 128. 129. 130. 131. 132. 133. 134. 135. 136. 137. 138. 139. 140.
 141. 142. 143. 144. 145. 146. 147. 148. 149. 150. 151. 152. 153. 154.
 155. 156. 157. 158. 159. 160. 161. 162. 163. 164. 165. 166. 167. 168.
 169. 170. 171. 172. 173. 174. 175. 176. 177. 178. 179. 180. 181. 182.
 183. 184. 185. 186. 187. 188. 189. 190. 191. 192. 193. 194. 195. 196.
 197. 

In [34]:
print(roi_labels[0])

1.0


In [30]:
roi_vectors_list = []

for roi in roi_labels:
    # Extract voxel values for current ROI
    roi_voxels = atlas[atlas == roi]
    
    # Reshape the voxels to (num_voxels, 1)
    reshaped_vector = roi_voxels.reshape(-1, 1)
    
    # Append the reshaped vector to the list
    roi_vectors_list.append(reshaped_vector)

print("Number of ROIs:", len(roi_vectors_list))
print("Shape of an example ROI vector:", roi_vectors_list[56].shape)
print("Example ROI vector:\n", roi_vectors_list[56])


Number of ROIs: 454
Shape of an example ROI vector: (2494, 1)
Example ROI vector:
 [[57.]
 [57.]
 [57.]
 ...
 [57.]
 [57.]
 [57.]]


In [ ]:
print(roi_vectors_list)

In [19]:
img_nifti.shape

(182, 218, 182)

In [21]:
# filter array by index

reshaped_vectors_list = []

# Step 3: Iterate over each index to extract and reshape vectors
for i in range(img_nifti.shape[0]):
    # Extract the vector for the current index
    vector = img_nifti[i]
    
    # Reshape the vector to (array.shape[1], 1)
    reshaped_vector = vector.reshape(-1, 1)
    
    # Append the reshaped vector to the list
    reshaped_vectors_list.append(reshaped_vector)

# Step 4: Convert the list to a NumPy array
reshaped_vectors_array = np.array(reshaped_vectors_list)

print("Reshaped vectors array:\n", reshaped_vectors_array)
for i in reshaped_vectors_list:
    print(i.shape)

Reshaped vectors array:
 [[[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 ...

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]
  ...
  [0.]
  [0.]
  [0.]]]
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1)
(39676, 1

In [20]:
reshaped_vectors_list = []

# Step 3: Iterate over each ROI to extract and reshape vectors
for i in range(img_nifti.shape[0]):
    # Extract the vector for the current ROI
    vector = img_nifti[i]
    
    # Reshape the vector to (N, 1)
    reshaped_vector = vector.reshape(-1, 1)
    
    # Append the reshaped vector to the list
    reshaped_vectors_list.append(reshaped_vector)

# Step 4: Convert the list to a NumPy array
reshaped_vectors_array = np.array(reshaped_vectors_list)

print("Shape of original atlas array:", img_nifti.shape)
print("Shape of reshaped vectors array:", reshaped_vectors_array.shape)
print("Example reshaped vector:\n", reshaped_vectors_array[0])

Shape of original atlas array: (182, 218, 182)
Shape of reshaped vectors array: (182, 39676, 1)
Example reshaped vector:
 [[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [48]:
# questo funziona. i extracted arrays containing volume for each roi

# Step 2: Get the unique ROI labels
roi_labels = np.unique(atlas)
roi_labels = roi_labels[roi_labels != 0]  # Assuming 0 is not a valid ROI

# Step 3: Initialize a dictionary to store coordinates for each ROI
roi_coordinates = {}

# Step 4: Extract coordinates for each ROI
for roi in roi_labels:
    # Create a mask for the current ROI
    roi_mask = atlas == roi
    
    # Get the coordinates of the voxels in this ROI
    coordinates = np.column_stack(np.where(roi_mask))
    
    # Store the coordinates in the dictionary
    roi_coordinates[roi] = coordinates

# Print the number of ROIs and the coordinates for an example ROI
print("Number of ROIs:", len(roi_coordinates))
example_roi = roi_labels[59]
print(f"Coordinates of ROI {example_roi}:\n", roi_coordinates[example_roi])


Number of ROIs: 454
Coordinates of ROI 60.0:
 [[114  37  53]
 [114  37  54]
 [114  38  53]
 [114  38  54]
 [115  37  53]
 [115  37  54]
 [115  38  50]
 [115  38  51]
 [115  38  52]
 [115  38  53]
 [115  38  54]
 [115  39  51]
 [115  39  52]
 [115  39  53]
 [115  39  54]
 [115  40  51]
 [115  40  52]
 [115  40  53]
 [115  40  54]
 [115  41  51]
 [115  41  52]
 [115  41  53]
 [115  41  54]
 [115  42  51]
 [115  42  52]
 [115  42  53]
 [115  42  54]
 [115  43  51]
 [116  36  50]
 [116  36  51]
 [116  36  52]
 [116  37  50]
 [116  37  51]
 [116  37  52]
 [116  37  53]
 [116  37  54]
 [116  38  50]
 [116  38  51]
 [116  38  52]
 [116  38  53]
 [116  38  54]
 [116  38  55]
 [116  38  56]
 [116  38  57]
 [116  39  51]
 [116  39  52]
 [116  39  53]
 [116  39  54]
 [116  39  55]
 [116  39  56]
 [116  39  57]
 [116  40  51]
 [116  40  52]
 [116  40  53]
 [116  40  54]
 [116  40  55]
 [116  40  56]
 [116  40  57]
 [116  41  51]
 [116  41  52]
 [116  41  53]
 [116  41  54]
 [116  42  51]
 [116  42

In [50]:
empty_array = np.empty(shape=(atlas.shape), dtype='object')